use clap::Args;
use colored::Colorize;
use std::path::PathBuf;

const CONFIG_FILENAME: &str = ".stylus-compat.toml";

const DEFAULT_CONFIG: &str = r#"# Configuration for stylus-registry.
# Generated by `stylus-registry init`.
#
# Every setting below is commented out and shows the CLI's built-in default.
# Uncomment and edit the ones you want to override. See docs/usage.md for
# the full list of accepted values.

# Minimum score (0-100) a crate or project must reach to pass in strict mode.
# threshold = 90

# Directory containing the known-crates registry data (known-compatible.toml,
# known-incompatible.toml). Equivalent to `--data-dir`.
# data_dir = "data"

# Default report format: "text" or "json". Equivalent to `--json`.
# format = "text"
"#;

#[derive(Args)]
pub struct InitArgs {
    /// Directory to write the config file into
    #[arg(long, default_value = ".")]
    pub path: PathBuf,

    /// Overwrite the config file if it already exists
    #[arg(long)]
    pub force: bool,
}

pub fn run(args: InitArgs) -> Result<(), Box<dyn std::error::Error>> {
    let config_path = args.path.join(CONFIG_FILENAME);

    if config_path.exists() && !args.force {
        println!(
            "{} {} already exists, skipping (use --force to overwrite)",
            "⚠".yellow(),
            config_path.display()
        );
        return Ok(());
    }

    std::fs::write(&config_path, DEFAULT_CONFIG)?;
    println!("{} wrote {}", "✓".green(), config_path.display());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn writes_config_file_when_absent() {
        let dir = tempdir().unwrap();

        run(InitArgs {
            path: dir.path().to_path_buf(),
            force: false,
        })
        .unwrap();

        let content = std::fs::read_to_string(dir.path().join(CONFIG_FILENAME)).unwrap();
        assert!(content.contains("# threshold = 90"));
        assert!(content.contains("# data_dir = \"data\""));
        assert!(content.contains("# format = \"text\""));
    }

    #[test]
    fn does_not_overwrite_existing_file_without_force() {
        let dir = tempdir().unwrap();
        let config_path = dir.path().join(CONFIG_FILENAME);
        std::fs::write(&config_path, "custom = true\n").unwrap();

        run(InitArgs {
            path: dir.path().to_path_buf(),
            force: false,
        })
        .unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert_eq!(content, "custom = true\n");
    }

    #[test]
    fn overwrites_existing_file_with_force() {
        let dir = tempdir().unwrap();
        let config_path = dir.path().join(CONFIG_FILENAME);
        std::fs::write(&config_path, "custom = true\n").unwrap();

        run(InitArgs {
            path: dir.path().to_path_buf(),
            force: true,
        })
        .unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.contains("# threshold = 90"));
    }
}
